# Uncomment the next line to define a global platform for your project

platform :ios, '12.2'

target 'FSUnionAdSDK-OCDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FSUnionAdSDK-OCDemo
  pod 'SDWebImage'

end
